# Generated by Django 5.2.17 on 2026-09-18 17:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('delay_minutes', models.PositiveIntegerField(default=0)),
                ('status_message', models.CharField(choices=[('ON_TIME', 'On Time'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled')], default='ON_TIME', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_status', to='stations.station')),
                ('next_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_status', to='stations.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='trains.train')),
            ],
            options={
                'unique_together': {('train', 'date')},
            },
        ),
    ]
