# Generated by Django 5.2.17 on 2026-09-22 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_alter_station_code'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainstatus',
            name='previous_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_status', to='stations.station'),
        ),
        migrations.AlterField(
            model_name='trainstatus',
            name='status_message',
            field=models.CharField(choices=[('ON_TIME', 'On Time'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('HALTED', 'Halted'), ('COMPLETED', 'Completed')], default='ON_TIME', max_length=20),
        ),
    ]
