# Generated by Django 5.2.17 on 2026-09-18 17:44

import django.db.models.deletion
import pnr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PNR',
            fields=[
                ('pnr_number', models.CharField(default=pnr.models.generate_pnr, max_length=10, primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_age', models.PositiveIntegerField()),
                ('date_of_journey', models.DateField()),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('WAITLISTED', 'Waitlisted'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20)),
                ('seat_number', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnr_destination', to='stations.station')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnr_source', to='stations.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.train')),
            ],
        ),
    ]
