# Generated by Django 5.2.17 on 2026-09-19 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_pnr_booking_date_of_journey_and_more'),
        ('pnr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pnr',
            name='date_of_journey',
        ),
        migrations.RemoveField(
            model_name='pnr',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='pnr',
            name='passenger_age',
        ),
        migrations.RemoveField(
            model_name='pnr',
            name='passenger_name',
        ),
        migrations.RemoveField(
            model_name='pnr',
            name='seat_number',
        ),
        migrations.RemoveField(
            model_name='pnr',
            name='source',
        ),
        migrations.RemoveField(
            model_name='pnr',
            name='train',
        ),
        migrations.AddField(
            model_name='pnr',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnr_record', to='bookings.booking'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('ticket_class', models.CharField(default='SL', max_length=10)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='bookings.booking')),
            ],
        ),
    ]
