# Generated by Django 5.2.17 on 2026-09-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnr', '0002_remove_pnr_date_of_journey_remove_pnr_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
