# Generated by Django 5.2.17 on 2026-09-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_pnr_booking_date_of_journey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_type', models.CharField(choices=[('EXPRESS', 'Express'), ('LOCAL', 'Local'), ('PASSENGER', 'Passenger'), ('SUPERFAST', 'Superfast')], max_length=20)),
                ('ticket_class', models.CharField(blank=True, help_text='Applicable class (e.g., SL, 3A, GN). Leave blank for default local fare.', max_length=10, null=True)),
                ('base_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_class',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
