# Generated by Django 5.2.17 on 2026-09-19 17:17

from django.db import migrations
from decimal import Decimal
import datetime

def backfill_legacy_bookings(apps, schema_editor):
    Booking = apps.get_model('bookings', 'Booking')
    
    # 1. Backfill legacy fare breakups
    legacy_fare_bookings = Booking.objects.filter(
        base_fare=Decimal('0.00'), 
        gst_amount=Decimal('0.00'), 
        fee_amount=Decimal('0.00'), 
        total_fare__gt=Decimal('0.00')
    )
    for b in legacy_fare_bookings:
        b.base_fare = b.total_fare
        b.save(update_fields=['base_fare'])

    # 2. Backfill null expires_at for PENDING bookings
    legacy_pending_bookings = Booking.objects.filter(status='PENDING', expires_at__isnull=True)
    for b in legacy_pending_bookings:
        b.expires_at = b.booking_date + datetime.timedelta(minutes=10)
        b.save(update_fields=['expires_at'])

def reverse_backfill(apps, schema_editor):
    Booking = apps.get_model('bookings', 'Booking')
    
    # Reversing this is tricky because we don't know which ones were legacy.
    # But to be safe, any booking where base_fare == total_fare and gst==0 and fee==0 could be reset.
    legacy_bookings = Booking.objects.filter(gst_amount=Decimal('0.00'), fee_amount=Decimal('0.00'))
    for b in legacy_bookings:
        if b.base_fare == b.total_fare:
            b.base_fare = Decimal('0.00')
            b.save(update_fields=['base_fare'])
        
    # We leave expires_at alone on reverse since it doesn't break anything.

class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_base_fare_booking_expires_at_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_legacy_bookings, reverse_backfill),
    ]
