# Generated by Django 5.2.17 on 2026-09-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_backfill_legacy_bookings'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'SUCCESS')), fields=('booking',), name='unique_success_payment'),
        ),
    ]
