# Generated by Django 5.2.17 on 2026-09-19 17:45

from django.db import migrations, models

def backfill_success(apps, schema_editor):
    Payment = apps.get_model('bookings', 'Payment')
    from django.db.models import Count
    
    # Check for duplicates
    duplicates = Payment.objects.filter(status='SUCCESS').values('booking').annotate(c=Count('id')).filter(c__gt=1)
    if duplicates.exists():
        print(f'\nWARNING: Found {duplicates.count()} bookings with multiple SUCCESS payments!')
        
    for p in Payment.objects.filter(status='SUCCESS'):
        p.success_for_booking = p.booking_id
        p.save(update_fields=['success_for_booking'])

def reverse_success(apps, schema_editor):
    Payment = apps.get_model('bookings', 'Payment')
    Payment.objects.update(success_for_booking=None)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_payment_unique_success_payment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='unique_success_payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='success_for_booking',
            field=models.IntegerField(blank=True, help_text='Set to booking_id if SUCCESS, else NULL for MySQL uniqueness', null=True, unique=True),
        ),
        migrations.RunPython(backfill_success, reverse_success),
    ]
