# Generated by Django 5.2.17 on 2026-09-22 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_remove_payment_unique_success_payment_and_more'),
        ('stations', '0004_alter_station_code'),
        ('trains', '0003_alter_train_train_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_destination', to='stations.station'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_source', to='stations.station'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='train',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trains.train'),
        ),
    ]
