# Generated by Django 5.2.17 on 2026-09-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_destination_alter_booking_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='journey_type',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('RETURN', 'Return')], default='SINGLE', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('UTS_PAPERLESS', 'UTS Paperless'), ('SEASON', 'Season'), ('TOURIST', 'Tourist')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='farerule',
            name='fare_slab',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farerule',
            name='is_fixed_fare',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farerule',
            name='journey_type',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('RETURN', 'Return')], default='SINGLE', max_length=10),
        ),
    ]
