# Generated by Django 5.2.17 on 2026-09-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_journey_type_booking_ticket_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_duration',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half Yearly'), ('YEARLY', 'Yearly'), ('1_DAY', '1 Day'), ('3_DAYS', '3 Days'), ('5_DAYS', '5 Days')], max_length=20, null=True),
        ),
    ]
