# Generated by Django 5.2.17 on 2026-09-18 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('train', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='trains.train')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField()),
                ('distance_from_source', models.PositiveIntegerField(help_text='Distance in km')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='routes.route')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
            ],
            options={
                'ordering': ['sequence_number'],
                'unique_together': {('route', 'station')},
            },
        ),
    ]
