# Generated by Django 5.2.17 on 2026-09-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_routestation_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestation',
            name='distance_from_source',
            field=models.PositiveIntegerField(blank=True, help_text='Distance in km', null=True),
        ),
    ]
