# Generated by Django 5.2.17 on 2026-09-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RapidAPIHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('train_number', models.CharField(blank=True, max_length=50, null=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('http_status', models.IntegerField()),
                ('success', models.BooleanField()),
                ('response_json', models.JSONField()),
            ],
            options={
                'db_table': 'rapid_api_history',
            },
        ),
    ]
