# Generated by Django 5.2.17 on 2026-09-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapidapihistory',
            name='request_params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
