# Generated by Django 5.2.17 on 2026-09-18 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('train_type', models.CharField(choices=[('EXPRESS', 'Express'), ('LOCAL', 'Local'), ('PASSENGER', 'Passenger'), ('SUPERFAST', 'Superfast')], default='EXPRESS', max_length=20)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_trains', to='stations.station')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_trains', to='stations.station')),
            ],
        ),
    ]
