# Generated by Django 5.2.17 on 2026-09-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='running_days',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
