# Generated by Django 5.2.17 on 2026-09-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_train_running_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='train_type',
            field=models.CharField(choices=[('EXPRESS', 'Express'), ('LOCAL', 'Local'), ('PASSENGER', 'Passenger'), ('SUPERFAST', 'Superfast'), ('SLOW', 'Slow'), ('FAST', 'Fast')], default='EXPRESS', max_length=20),
        ),
    ]
