# Generated by Django 5.2.17 on 2026-09-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_station_latitude_station_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='zone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
